---
title: "Evaluation"
author: "Hao Huang"
date: '2022-07-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load 
## load packages
```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(Seurat)
  library(caret)
  library(kknn)
  
  library(scater)
  library(tidyverse)
  library(dplyr)
  
  library(glue)
  library(stringr)
})
```

useful function
```{r}
source("../../Utils/utils.R")
source("../../Utils/Classification_methods/doEval.R")
```

# KKNN
## Deep learning methods evaluation loop 
```{r}
nn_methods = c("DeepLift", "GradientShap", "LRP","FeatureAblation", "Occlusion","Lime")
```


```{r}
n=1 # seed number 1
j=1 # repeat times
nCells=200
while(j<=10){
  for(nGroups in c(10,20)){#seq(5,20,5)
    for (imbratio in c(1/2, 1/4, 1/10)){
      # read sce
      sce = readRDS(glue("../../Data/Simulation/Tabula_muris/Setting3/nGroups_{nGroups}/imbratio_{imbratio}/Simulation_setting3_nCellsMajor_200_nGroups_{nGroups}_iteration{j}_imbalanceRatio_1_{imbratio}.rds"))
      rownames(sce) = str_replace_all(rownames(sce), "_", "-") # compatibale with seurat
      
      # split 
      res.split = train_test_split(rna = sce, cty = sce$cellTypes, seedInput = 1234)
      train.rna = res.split$train.rna
      train.cty = res.split$train.cty
      test.rna = res.split$test.rna
      test.cty = res.split$test.cty
      cellTypes = levels(as.factor(train.rna$cellTypes))
      
      # iteration over methods, results
      for (method in nn_methods){
        #work around of file name
        file_list = list.files(glue("../../Result/Fs_marker/Nn/Setting3/{method}/nGroups_{nGroups}_imb_{imbratio}_iteration{j}/"))
        for (topN in c(5, 10, 20)) { #5, 10, 20, 50, 100
          union_genes = c()
          for (anchor_celltype_num in (c(1:length(cellTypes))-1)){
            anchor_celltype = cellTypes[anchor_celltype_num+1]
            
            # work 
            file = file_list[grep(anchor_celltype, file_list)]
            res_fs = read_csv(glue("../../Result/Fs_marker/Nn/Setting3/{method}/nGroups_{nGroups}_imb_{imbratio}_iteration{j}/{file}"), show_col_types = FALSE)
            #res_fs = read.csv(glue("../../Result/Fs_marker/Nn_2/Setting1/{method}/dataset_seeds_{n}/fs.all.{method}.celltype{anchor_celltype_num}.{anchor_celltype}..seed1234.csv"), row.names = 1)
            gene_names = c(res_fs[,1])[[1]]
            gene_names = str_replace_all(gene_names, "_","-")
            a = gene_names[1:topN]
            union_genes = c(union_genes, a)
          }
          union_genes = unique(union_genes)
          tmp_sce = train.rna[union_genes,]
          set.seed(1)
          res = doKKnn_simple_union(tmp_sce, tmp_sce$cellTypes, test.rna[union_genes,],  test.cty)
          cat("finished KKnn")
          print("Accuracy is:")
          print(res[[1]][,1][1])
          dir.create(glue("../../Result/Classification/KKnn/Setting3/top{topN}"), showWarnings = FALSE)
          dir.create(glue("../../Result/Classification/KKnn/Setting3/top{topN}/{method}"), showWarnings = FALSE)
          saveRDS(res, file = glue("../../Result/Classification/KKnn/Setting3/top{topN}/{method}/KKnn_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
          }
        }
    cat(glue("==================finished {n} datasets================= \n"))
    n=n+1
    }
  }
  j=j+1
}
```



## Traditional methods evaluation loop
```{r}
trad_methods = c("runDESeq2", "runLimmavoom", "runScDD")
```

```{r}
n=1 # seed number 1
j=1 # repeat times
while(j<=10){
  for(nGroups in c(10,20)){#seq(5,20,5)
    for (imbratio in c(1/2, 1/4, 1/10)){
      # read sce
      sce = readRDS(glue("../../Data/Simulation/Tabula_muris/Setting3/nGroups_{nGroups}/imbratio_{imbratio}/Simulation_setting3_nCellsMajor_200_nGroups_{nGroups}_iteration{j}_imbalanceRatio_1_{imbratio}.rds"))
    rownames(sce) = str_replace_all(rownames(sce), "_", "-") # compatibale with seurat
    
    # split 
    res.split = train_test_split(rna = sce, cty = sce$cellTypes, seedInput = 1234)
    train.rna = res.split$train.rna
    train.cty = res.split$train.cty
    test.rna = res.split$test.rna
    test.cty = res.split$test.cty
    cellTypes = levels(as.factor(train.rna$cellTypes))
      # iteration over methods, results
      for (method in trad_methods){
        res_fs = readRDS(glue("../../Result/Fs_marker/Traditional/Setting3/{method}/Res_{method}_Simulation_setting3_nGroups_{nGroups}_imbratio_{imbratio}_iteration{j}.rds"))
        for (topN in c(5,10,20)){ #5, 10, 20, 50, 100
          union_genes = c()
          for (anchor_celltype_num in (c(1:length(cellTypes))-1)){
              anchor_celltype = cellTypes[anchor_celltype_num+1]
              
              tmp_res_fs = res_fs$result[[anchor_celltype_num+1]]
              rownames(tmp_res_fs) = str_replace_all(rownames(tmp_res_fs), "_","-") # covert this, to make seurat and non-seruat methods compatiable
              a = rownames(tmp_res_fs)[1:topN]
              union_genes = c(union_genes, a)
          }
          union_genes = unique(union_genes)
          tmp_sce = train.rna[union_genes,]
          set.seed(1)
          res = doKKnn_simple_union(tmp_sce, tmp_sce$cellTypes, test.rna[union_genes,],  test.cty)
          cat("finished KKnn")
          print("Accuracy is:")
          print(res[[1]][,1][1])
          dir.create(glue("../../Result/Classification/KKnn/Setting3/top{topN}"), showWarnings = FALSE)
          dir.create(glue("../../Result/Classification/KKnn/Setting3/top{topN}/{method}"), showWarnings = FALSE)
          saveRDS(res, file = glue("../../Result/Classification/KKnn/Setting3/top{topN}/{method}/KKnn_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
          }
        }
    cat(glue("==================finished {n} datasets================= \n"))
    n=n+1
    }
  }
  j=j+1
}
```



# SVM
## Deep learning methods evaluation loop 
```{r}
nn_methods = c("DeepLift", "GradientShap", "LRP","FeatureAblation", "Occlusion","Lime")
```


```{r}
n=1 # seed number 1
j=1 # repeat times
nCells=200
while(j<=10){
  for(nGroups in c(10,20)){#seq(5,20,5)
    for (imbratio in c(1/2, 1/4, 1/10)){
      # read sce
      sce = readRDS(glue("../../Data/Simulation/Tabula_muris/Setting3/nGroups_{nGroups}/imbratio_{imbratio}/Simulation_setting3_nCellsMajor_200_nGroups_{nGroups}_iteration{j}_imbalanceRatio_1_{imbratio}.rds"))
      rownames(sce) = str_replace_all(rownames(sce), "_", "-") # compatibale with seurat
      
      # split 
      res.split = train_test_split(rna = sce, cty = sce$cellTypes, seedInput = 1234)
      train.rna = res.split$train.rna
      train.cty = res.split$train.cty
      test.rna = res.split$test.rna
      test.cty = res.split$test.cty
      cellTypes = levels(as.factor(train.rna$cellTypes))
      
      # iteration over methods, results
      for (method in nn_methods){
        #work around of file name
        file_list = list.files(glue("../../Result/Fs_marker/Nn/Setting3/{method}/nGroups_{nGroups}_imb_{imbratio}_iteration{j}/"))
        for (topN in c(5, 10, 20)) { #5, 10, 20, 50, 100
          union_genes = c()
          for (anchor_celltype_num in (c(1:length(cellTypes))-1)){
            anchor_celltype = cellTypes[anchor_celltype_num+1]
            
            # work 
            file = file_list[grep(anchor_celltype, file_list)]
            res_fs = read_csv(glue("../../Result/Fs_marker/Nn/Setting3/{method}/nGroups_{nGroups}_imb_{imbratio}_iteration{j}/{file}"), show_col_types = FALSE)
            #res_fs = read.csv(glue("../../Result/Fs_marker/Nn_2/Setting1/{method}/dataset_seeds_{n}/fs.all.{method}.celltype{anchor_celltype_num}.{anchor_celltype}..seed1234.csv"), row.names = 1)
            gene_names = c(res_fs[,1])[[1]]
            gene_names = str_replace_all(gene_names, "_","-")
            a = gene_names[1:topN]
            union_genes = c(union_genes, a)
          }
          union_genes = unique(union_genes)
          tmp_sce = train.rna[union_genes,]
          set.seed(1)
          res = doSvm_simple_union(tmp_sce, tmp_sce$cellTypes, test.rna[union_genes,],  test.cty)
          cat("finished SVM")
          print("Accuracy is:")
          print(res[[1]][,1][1])
          dir.create(glue("../../Result/Classification/SVM/Setting3/top{topN}"), showWarnings = FALSE)
          dir.create(glue("../../Result/Classification/SVM/Setting3/top{topN}/{method}"), showWarnings = FALSE)
          saveRDS(res, file = glue("../../Result/Classification/SVM/Setting3/top{topN}/{method}/SVM_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
          }
        }
    cat(glue("==================finished {n} datasets================= \n"))
    n=n+1
    }
  }
  j=j+1
}
```



## Traditional methods evaluation loop
```{r}
trad_methods = c("runDESeq2", "runLimmavoom", "runScDD")
```

```{r}
n=1 # seed number 1
j=1 # repeat times
while(j<=10){
  for(nGroups in c(10,20)){#seq(5,20,5)
    for (imbratio in c(1/2, 1/4, 1/10)){
      # read sce
      sce = readRDS(glue("../../Data/Simulation/Tabula_muris/Setting3/nGroups_{nGroups}/imbratio_{imbratio}/Simulation_setting3_nCellsMajor_200_nGroups_{nGroups}_iteration{j}_imbalanceRatio_1_{imbratio}.rds"))
    rownames(sce) = str_replace_all(rownames(sce), "_", "-") # compatibale with seurat
    
    # split 
    res.split = train_test_split(rna = sce, cty = sce$cellTypes, seedInput = 1234)
    train.rna = res.split$train.rna
    train.cty = res.split$train.cty
    test.rna = res.split$test.rna
    test.cty = res.split$test.cty
    cellTypes = levels(as.factor(train.rna$cellTypes))
      # iteration over methods, results
      for (method in trad_methods){
        res_fs = readRDS(glue("../../Result/Fs_marker/Traditional/Setting3/{method}/Res_{method}_Simulation_setting3_nGroups_{nGroups}_imbratio_{imbratio}_iteration{j}.rds"))
        for (topN in c(5,10,20)){ #5, 10, 20, 50, 100
          union_genes = c()
          for (anchor_celltype_num in (c(1:length(cellTypes))-1)){
              anchor_celltype = cellTypes[anchor_celltype_num+1]

              tmp_res_fs = res_fs$result[[anchor_celltype_num+1]]
              rownames(tmp_res_fs) = str_replace_all(rownames(tmp_res_fs), "_","-") # covert this, to make seurat and non-seruat methods compatiable
              a = rownames(tmp_res_fs)[1:topN]
              union_genes = c(union_genes, a)
          }
          union_genes = unique(union_genes)
          tmp_sce = train.rna[union_genes,]
          set.seed(1)
          res = doSvm_simple_union(tmp_sce, tmp_sce$cellTypes, test.rna[union_genes,],  test.cty)
          cat("finished SVM")
          print("Accuracy is:")
          print(res[[1]][,1][1])
          dir.create(glue("../../Result/Classification/SVM/Setting3/top{topN}"), showWarnings = FALSE)
          dir.create(glue("../../Result/Classification/SVM/Setting3/top{topN}/{method}"), showWarnings = FALSE)
          saveRDS(res, file = glue("../../Result/Classification/SVM/Setting3/top{topN}/{method}/SVM_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
          }
        }
    cat(glue("==================finished {n} datasets================= \n"))
    n=n+1
    }
  }
  j=j+1
}
```

