---
title: "Setting3_balloonplot"
author: "Hao Huang"
date: "03/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load packages
```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(Seurat)
  library(caret)
  library(kknn)
  
  library(scater)
  library(tidyverse)
  library(dplyr)
  
  library(glue)
  library(stringr)
  library(ggplot2)
  library(ggpubr)
  library(ggridges)
})
```

useful function
```{r}
source("../../Utils/utils.R")
source("../../Utils/Classification_methods/doEval.R")
```

```{r}
topN = 20
```

# Classification
```{r}
classification_method = "SVM" # KKnn"SVM"
```




# Tabula muris
```{r}
sce = readRDS("../../Data/Processed/Tabula_muris/FS/sce_TM_FAC_processed_HH_no_logcount.rds")
sce$celltype = sce$cell_ontology_class

nCellsinEachGroup=data.frame(table(sce$celltype))
groups=nCellsinEachGroup[nCellsinEachGroup$Freq>=300,]
celltype=sce$celltype # cell type vector
names(celltype)=colnames(sce) # cell id vector
```

```{r}
# traditional methods
trad_methods = c("runDESeq2", "runLimmavoom", "runScDD")
df <- data.frame()
for (method in trad_methods){
  n=1
  j=1 # repeat times
  while(j<=10){
    selectedGroup_major <- c()
    selectedGroup_minor <- c()
    to_select = droplevels(groups$Var1)
    for(nGroups in c(10,20)){#seq(5,20,5)
      set.seed(n)
      selectedGroup_major = c(selectedGroup_major, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_major]
      selectedGroup_minor = c(selectedGroup_minor, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_minor]
      for (imbratio in c(1/2,1/4,1/10)){#1/2, 1/4, 1/10
        tmp = readRDS(glue("../../Result/Classification/{classification_method}/Setting3/top{topN}/{method}/{classification_method}_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
        tmp[[2]][is.na(tmp[[2]])]=0
        tmp_mean  = rowMeans(tmp[[2]][,colnames(tmp[[2]]) %in%  selectedGroup_minor] )
        tmp_res <- c(tmp_mean[[7]], nGroups, imbratio, j, method, "traditional")
        df <- rbind(df, tmp_res)
      }
      n=n+1
    }
    j=j+1
  }
cat(glue("finished {method}  \n"))
}
  df <- as.data.frame(df)
  colnames(df) <- c("Value", "nGroups", "imbratio", "Iteration", "Method", "Category")
  df$Value <- as.numeric(df$Value)
  #df$nGroups <- factor(df$nGroups)
  #df$nCells <- factor(df$nCells)
  
  df.trad <- df
```

```{r}
# deep learning methods
nn_methods = c("DeepLift",  "GradientShap","LRP", "FeatureAblation", "Occlusion", "Lime") #, "Lime"
dl_cat <- c(rep("Deep learning - gradient based", 3), rep("Deep learning - perturbation", 3))
dl_cat_num = 1
df <- data.frame()
for (method in nn_methods){
n=1
  j=1 # repeat times
  while(j<=10){
    selectedGroup_major <- c()
    selectedGroup_minor <- c()
    to_select = droplevels(groups$Var1)
    for(nGroups in c(10,20)){#seq(5,20,5)
      set.seed(n)
      selectedGroup_major = c(selectedGroup_major, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_major]
      selectedGroup_minor = c(selectedGroup_minor, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_minor]
      for (imbratio in c(1/2,1/4,1/10)){#1/2, 1/4, 1/10
        tmp = readRDS(glue("../../Result/Classification/{classification_method}/Setting3/top{topN}/{method}/{classification_method}_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
        tmp[[2]][is.na(tmp[[2]])]=0
        tmp_mean  = rowMeans(tmp[[2]][,colnames(tmp[[2]]) %in%  selectedGroup_minor] )
        tmp_res <- c(tmp_mean[[7]], nGroups, imbratio, j, method, dl_cat[dl_cat_num])
        df <- rbind(df, tmp_res)
      }
      
      
      n=n+1
    }
    j=j+1
  }
  dl_cat_num = dl_cat_num+1
  cat(glue("finished {method}  \n"))
}
df <- as.data.frame(df)
colnames(df) <- c("Value", "nGroups", "imbratio", "Iteration", "Method", "Category")
df$Value <- as.numeric(df$Value)

df.nn <- df
```

```{r}
# combine 
df.combine = rbind(df.nn, df.trad)
df.combine$Category = factor(df.combine$Category)
df.combine$Method = factor(df.combine$Method, levels = c(nn_methods, trad_methods))
df.combine$nGroups = factor(df.combine$nGroups)
df.combine$imbratio = factor(df.combine$imbratio, levels = c(1/2, 1/4, 1/10))

df.combine$data = "TM"
df.combine.20 = df.combine[df.combine$nGroups==20,]
df.combine.20.tm <- df.combine.20
```

# Tabula sapiens
```{r}
sce = readRDS("../../Data/Processed/Tabula_sapiens//FS/sce_TS_FAC_processed_no_logcount.rds")
sce$celltype = sce$cell_ontology_class

nCellsinEachGroup=data.frame(table(sce$celltype))
groups=nCellsinEachGroup[nCellsinEachGroup$Freq>=300,]
celltype=sce$celltype # cell type vector
names(celltype)=colnames(sce) # cell id vector
```

```{r}
# traditional methods
trad_methods = c("runDESeq2", "runLimmavoom", "runScDD")
df <- data.frame()
for (method in trad_methods){
  n=1
  j=1 # repeat times
  while(j<=10){
    selectedGroup_major <- c()
    selectedGroup_minor <- c()
    to_select = droplevels(groups$Var1)
    for(nGroups in c(10,20)){#seq(5,20,5)
      set.seed(n)
      selectedGroup_major = c(selectedGroup_major, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_major]
      selectedGroup_minor = c(selectedGroup_minor, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_minor]
      for (imbratio in c(1/2,1/4,1/10)){#1/2, 1/4, 1/10
        tmp = readRDS(glue("../../Result/TS_Classification/{classification_method}/Setting3/top{topN}/{method}/{classification_method}_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
        tmp[[2]][is.na(tmp[[2]])]=0
        tmp_mean  = rowMeans(tmp[[2]][,colnames(tmp[[2]]) %in%  selectedGroup_minor] )
        tmp_res <- c(tmp_mean[[1]], nGroups, imbratio, j, method, "traditional")
        df <- rbind(df, tmp_res)
      }
      n=n+1
    }
    j=j+1
  }
cat(glue("finished {method}  \n"))
}
  df <- as.data.frame(df)
  colnames(df) <- c("Value", "nGroups", "imbratio", "Iteration", "Method", "Category")
  df$Value <- as.numeric(df$Value)
  #df$nGroups <- factor(df$nGroups)
  #df$nCells <- factor(df$nCells)
  
  df.trad <- df
```

```{r}
# deep learning methods
nn_methods = c("DeepLift",  "GradientShap","LRP", "FeatureAblation", "Occlusion", "Lime") 
dl_cat <- c(rep("Deep learning - gradient based", 8), rep("Deep learning - perturbation", 3), "Deep laarning - optimization")
dl_cat_num = 1
df <- data.frame()
for (method in nn_methods){
n=1
  j=1 # repeat times
  while(j<=10){
    selectedGroup_major <- c()
    selectedGroup_minor <- c()
    to_select = droplevels(groups$Var1)
    for(nGroups in c(10,20)){#seq(5,20,5)
      set.seed(n)
      selectedGroup_major = c(selectedGroup_major, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_major]
      selectedGroup_minor = c(selectedGroup_minor, as.character(sample(to_select, 5)))
      to_select = to_select[! to_select %in% selectedGroup_minor]
      for (imbratio in c(1/2,1/4,1/10)){#1/2, 1/4, 1/10
        tmp = readRDS(glue("../../Result/TS_Classification/{classification_method}/Setting3/top{topN}/{method}/{classification_method}_top{topN}_result_nGroups_{nGroups}_imb_{imbratio}_iteration{j}.rds"))
        tmp[[2]][is.na(tmp[[2]])]=0
        tmp_mean  = rowMeans(tmp[[2]][,colnames(tmp[[2]]) %in%  selectedGroup_minor] )
        tmp_res <- c(tmp_mean[[1]], nGroups, imbratio, j, method, dl_cat[dl_cat_num])
        df <- rbind(df, tmp_res)
      }
      
      
      n=n+1
    }
    j=j+1
  }
  dl_cat_num = dl_cat_num+1
  cat(glue("finished {method}  \n"))
}
df <- as.data.frame(df)
colnames(df) <- c("Value", "nGroups", "imbratio", "Iteration", "Method", "Category")
df$Value <- as.numeric(df$Value)

df.nn <- df
```

```{r}
# combine 
df.combine = rbind(df.nn, df.trad)
df.combine$Category = factor(df.combine$Category)
df.combine$Method = factor(df.combine$Method, levels = c(nn_methods, trad_methods))
df.combine$nGroups = factor(df.combine$nGroups)
df.combine$imbratio = factor(df.combine$imbratio, levels = c(1/2, 1/4, 1/10))

df.combine$data = "TS"
df.combine.20 = df.combine[df.combine$nGroups==20,]
df.combine.20.ts <- df.combine.20
```

# combine F1 balloonplot nGroups 20
```{r, fig.width=3}
df.ballon.tm <- aggregate(Value ~ Method + imbratio + data, data=df.combine.20.tm, FUN=median)
df.ballon.2.tm <- data.frame()
for (i in c(0.5, 0.25, 0.1)) {
  df.tmp <- df.ballon.tm[df.ballon.tm$imbratio ==i,]
  df.tmp$Rank <- rank(df.tmp$Value)
  df.ballon.2.tm <- rbind(df.ballon.2.tm, df.tmp)
}

df.ballon.ts <- aggregate(Value ~ Method + imbratio + data, data=df.combine.20.ts, FUN=median)
df.ballon.2.ts <- data.frame()
for (i in c(0.5, 0.25, 0.1)) {
  df.tmp <- df.ballon.ts[df.ballon.ts$imbratio ==i,]
  df.tmp$Rank <- rank(df.tmp$Value)
  df.ballon.2.ts <- rbind(df.ballon.2.ts, df.tmp)
}


df.ballon.2 <- rbind(df.ballon.2.tm, df.ballon.2.ts)
df.ballon.2$imbratio <- factor(df.ballon.2$imbratio  , levels = c(0.5,0.25,0.1))
df.ballon.2$Method <- factor(df.ballon.2$Method, levels = c(nn_methods,trad_methods))
#ggballoonplot(data=df.ballon.2, x="Method", y="nGroups", size="Rank", color="data", fill = "NA")
p1 = ggballoonplot(data=df.ballon.2, x="Method", y="imbratio", size="Rank", color="data", fill = "NA")+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
p1
ggsave(p1, width=5, height = 4, filename = glue("../../Figures/Combined_Setting3/Classification/{classification_method}_Setting3_balloonplot_top{topN}_nGroups20_F1.pdf"))
```
